name: mobile_day
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.10+1
  get: ^4.6.5
  speech_to_text: ^6.0.0

flutter_native_splash:
  color: "#002958"
  image: assets/logo.png

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/luigi.png
    - assets/logo.png
 
  uses-material-design: true

 